db.driver-class-name: org.postgresql.Driver
db.url: jdbc:postgresql://localhost:5432/task
db.userName: admin
db.password: 111

liquibase.enabled: true
liquibase.change-log: db/changelog/db.changelog-master.yaml
liquibase.liquibase-schema: migration
